cmake_minimum_required(VERSION 3.21)

# ------------------------------------------------------------------------------
# Project
# ------------------------------------------------------------------------------

project(obz VERSION 0.1.0 LANGUAGES CXX)

# ------------------------------------------------------------------------------
# Options
# ------------------------------------------------------------------------------

option(OBZ_BUILD_TESTS "Build obz tests" ON)
option(OBZ_BUILD_EXAMPLES "Build obz examples" ON)

# ------------------------------------------------------------------------------
# Libraries
# ------------------------------------------------------------------------------

add_subdirectory(libs/blocking_queue)

# ------------------------------------------------------------------------------
# Tests
# ------------------------------------------------------------------------------

if (OBZ_BUILD_TESTS)
    enable_testing()
    add_subdirectory(tests)
endif()