# ------------------------------------------------------------------------------
# Library target
# ------------------------------------------------------------------------------

add_library(obz_http
    src/request.cpp
    src/response.cpp
    src/server.cpp
)

# ------------------------------------------------------------------------------
# Public alias
# ------------------------------------------------------------------------------

add_library(obz::http ALIAS obz_http)

# ------------------------------------------------------------------------------
# Include directories
# ------------------------------------------------------------------------------

target_include_directories(obz_http
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)

# ------------------------------------------------------------------------------
# Link dependencies
# ------------------------------------------------------------------------------

target_link_libraries(obz_http
    PUBLIC
        obz::transport
)

# ------------------------------------------------------------------------------
# Compile features
# ------------------------------------------------------------------------------

target_compile_features(obz_http
    PUBLIC
        cxx_std_20
)
