# ------------------------------------------------------------------------------
# Library target
# ------------------------------------------------------------------------------

add_library(obz_endian INTERFACE)

# ------------------------------------------------------------------------------
# Public alias
# ------------------------------------------------------------------------------

add_library(obz::endian ALIAS obz_endian)

# ------------------------------------------------------------------------------
# Compile features
# ------------------------------------------------------------------------------

target_compile_features(obz_endian
    INTERFACE
        cxx_std_20
)

obz_install_library(obz_endian endian "${CMAKE_CURRENT_SOURCE_DIR}/include")
